"""create initial schema

Revision ID: dee37a9cc58e
Revises: 
Create Date: 2026-08-22 00:45:22.038557

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'dee37a9cc58e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('weekly', 'manual', name='batchkind', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stats', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_kind'), ['kind'], unique=False)

    op.create_table('maps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('beatsaver_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('song_author', sa.String(length=128), nullable=True),
    sa.Column('mapper', sa.String(length=128), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('candidate', 'qualified', 'ranked', 'removed', name='mapstatus', native_enum=False, length=16), nullable=False),
    sa.Column('submitted_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maps')),
    sa.UniqueConstraint('hash', name=op.f('uq_maps_hash'))
    )
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_maps_beatsaver_id'), ['beatsaver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_maps_status'), ['status'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ss_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('hmd', sa.String(length=32), nullable=True),
    sa.Column('pp_total', sa.Float(), nullable=False),
    sa.Column('pp_acc', sa.Float(), nullable=False),
    sa.Column('pp_tech', sa.Float(), nullable=False),
    sa.Column('pp_speed', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_rank'), ['rank'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_ss_id'), ['ss_id'], unique=True)

    op.create_table('staff_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_users'))
    )
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staff_users_discord_id'), ['discord_id'], unique=True)

    op.create_table('difficulties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map_id', sa.Integer(), nullable=False),
    sa.Column('characteristic', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('njs', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Integer(), nullable=True),
    sa.Column('max_pp', sa.Float(), nullable=True),
    sa.Column('total_stars', sa.Float(), nullable=True),
    sa.Column('acc_stars', sa.Float(), nullable=True),
    sa.Column('tech_stars', sa.Float(), nullable=True),
    sa.Column('speed_stars', sa.Float(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('style_tags', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=True),
    sa.Column('ranked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['map_id'], ['maps.id'], name=op.f('fk_difficulties_map_id_maps'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_difficulties')),
    sa.UniqueConstraint('map_id', 'characteristic', 'name', name='uq_difficulties_map_char_name')
    )
    with op.batch_alter_table('difficulties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_difficulties_map_id'), ['map_id'], unique=False)
        batch_op.create_index('ix_difficulties_total_stars', ['total_stars'], unique=False)

    op.create_table('rank_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week', sa.String(length=10), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pp_total', sa.Float(), nullable=True),
    sa.Column('pp_acc', sa.Float(), nullable=True),
    sa.Column('pp_tech', sa.Float(), nullable=True),
    sa.Column('pp_speed', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_rank_snapshots_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rank_snapshots')),
    sa.UniqueConstraint('week', 'player_id', name='uq_rank_snapshots_week_player')
    )
    with op.batch_alter_table('rank_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rank_snapshots_player_id'), ['player_id'], unique=False)
        batch_op.create_index('ix_rank_snapshots_week_rank', ['week', 'rank'], unique=False)

    op.create_table('rating_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('total_stars_before', sa.Float(), nullable=True),
    sa.Column('total_stars_after', sa.Float(), nullable=True),
    sa.Column('acc_stars_before', sa.Float(), nullable=True),
    sa.Column('acc_stars_after', sa.Float(), nullable=True),
    sa.Column('tech_stars_before', sa.Float(), nullable=True),
    sa.Column('tech_stars_after', sa.Float(), nullable=True),
    sa.Column('speed_stars_before', sa.Float(), nullable=True),
    sa.Column('speed_stars_after', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=True),
    sa.Column('applied_by', sa.String(length=64), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_rating_history_batch_id_batches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulties.id'], name=op.f('fk_rating_history_difficulty_id_difficulties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rating_history'))
    )
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rating_history_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rating_history_difficulty_id'), ['difficulty_id'], unique=False)

    op.create_table('reweight_suggestions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('observed_acc', sa.Float(), nullable=True),
    sa.Column('expected_acc', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('delta_stars', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'applied', 'rejected', name='suggestionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulties.id'], name=op.f('fk_reweight_suggestions_difficulty_id_difficulties'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reweight_suggestions'))
    )
    with op.batch_alter_table('reweight_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reweight_suggestions_difficulty_id'), ['difficulty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reweight_suggestions_status'), ['status'], unique=False)

    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('difficulty_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('acc', sa.Float(), nullable=True),
    sa.Column('modifiers', sa.String(length=64), nullable=True),
    sa.Column('full_combo', sa.Boolean(), nullable=False),
    sa.Column('pp', sa.Float(), nullable=True),
    sa.Column('pp_acc', sa.Float(), nullable=True),
    sa.Column('pp_tech', sa.Float(), nullable=True),
    sa.Column('pp_speed', sa.Float(), nullable=True),
    sa.Column('leaderboard_rank', sa.Integer(), nullable=True),
    sa.Column('time_set', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['difficulty_id'], ['difficulties.id'], name=op.f('fk_scores_difficulty_id_difficulties'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_scores_player_id_players'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scores')),
    sa.UniqueConstraint('player_id', 'difficulty_id', 'time_set', name='uq_scores_player_difficulty_time_set')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scores_difficulty_id'), ['difficulty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scores_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scores_player_id'))
        batch_op.drop_index(batch_op.f('ix_scores_difficulty_id'))

    op.drop_table('scores')
    with op.batch_alter_table('reweight_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reweight_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_reweight_suggestions_difficulty_id'))

    op.drop_table('reweight_suggestions')
    with op.batch_alter_table('rating_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rating_history_difficulty_id'))
        batch_op.drop_index(batch_op.f('ix_rating_history_batch_id'))

    op.drop_table('rating_history')
    with op.batch_alter_table('rank_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_rank_snapshots_week_rank')
        batch_op.drop_index(batch_op.f('ix_rank_snapshots_player_id'))

    op.drop_table('rank_snapshots')
    with op.batch_alter_table('difficulties', schema=None) as batch_op:
        batch_op.drop_index('ix_difficulties_total_stars')
        batch_op.drop_index(batch_op.f('ix_difficulties_map_id'))

    op.drop_table('difficulties')
    with op.batch_alter_table('staff_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staff_users_discord_id'))

    op.drop_table('staff_users')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_ss_id'))
        batch_op.drop_index(batch_op.f('ix_players_rank'))
        batch_op.drop_index(batch_op.f('ix_players_country'))

    op.drop_table('players')
    with op.batch_alter_table('maps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_maps_status'))
        batch_op.drop_index(batch_op.f('ix_maps_beatsaver_id'))

    op.drop_table('maps')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_kind'))

    op.drop_table('batches')
    # ### end Alembic commands ###
